### ISSUE TITLE
[BUG] Not all keys copied

### ISSUE THREAD

**Issue by WolfSkin0** [Foxlider/FASTER#1]
**Describe the bug**
Not all keys are being copied from their mod folders to the root folder if they are not in the <mod>/keys subdirectory

**To Reproduce**
Steps to reproduce the behaviour:
1. Download a mod where key is not in <mod>/keys subdir (e.g. @ACE_Interaction_Menu_Expansion which has UPSL.bikey key)
2. Click on "Copy Mods Keys" button
3. Look into keys folder and notice lack of key

**Expected behaviour**
All keys to be mapped and copied over

**Actual behaviour**
Only keys in /keys subdir copied over

**Screenshots**
N/A

**OS Version (required):**
 - OS: Windows Server 2019 Standard
 - Version: 17763.rs5_release.180914-1434

**Additional context**
Could probably be solved by mapping each mod folder for the *.bikey pattern to a depth of 2 or 3. It might take a tad longer, but it ensures all keys get copied, because otherwise having to trawl through all the folders to ensure all keys are copied defeats the point of the copy button

**Comment by Foxlider** [comment]
Fixed in release
