### ISSUE TITLE
custom Steam Protocol Max Data Size doesn't get uncommented in the config file

### ISSUE THREAD

**Issue by oldLucke** [Foxlider/FASTER#10]
**Describe the bug**
When setting a custom value for the `Steam Protocol Max Data Size `the paramter doesn't get uncommented in the server_config.cfg

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Server tab
2. Click on Server Advanced
3. Enter a custom value in `Steam Protocol Max Data Size `
4. Save the changes

**Expected behaviour**
The `steamProtocolMaxDataSize ` parameter in the server_config.cfg should be uncommented.

**Actual behaviour**
The `steamProtocolMaxDataSize ` parameter in the server_config.cfg is still commented.

**Comment by Foxlider** [comment]
Will be fixed on release. 

In the meantime, you can edit manually the server.cfg in the bottom panel
Thanks for the report !
