### ISSUE TITLE
Mod preset more then 25

### ISSUE THREAD

**Issue by Otarius-big** [Foxlider/FASTER#101]
when i am trying join on server launched with Faster tool with 30 or more mods game can find modlist with arma launcher , there no mod list and all time i must add modlist manualy that join server with server mods

**Comment by PulsarNeutronStar** [comment]
are you familiar with the concept of key verification?

**Comment by Foxlider** [comment]
Also it's the SteamProtocolMaxDataSize option in the [ServerAdvanced](https://github.com/Foxlider/FASTER/wiki/Profile-Page#server-advanced) menu

**Comment by mwpowellhtx** [comment]
Think I am bumping into the same issue. Upped `SteamProtocolMaxDataSize` to something like `4096` but still punting me out on key challenges:

```
...are not signed by a key accepted by this server. To play on this server, remove listed files or install additional accepted keys.
```

Verified I have the `*.bikeys` in the appropriate `.\keys` folder (I "think"?), AFAIK. Do I need the `*.bisigns` a well? Full relative path:

```
.\steamapps\common\Arma 3 Server\Servers\_a6544a01f83243b19497d0933bedcbb1\keys
```

Server side:

```
 2:01:13 Warning: Steam Query data overflow, Mods/Signatures will not be correctly received by clients. Remove unused mods or change your server configuration to allow for more data to be sent.
```

But this much appears to have subsided with couple of upped _server_ or _performance_ tweaks.
