### ISSUE TITLE
[FEATURE] Add scrolling to the profiles list

### ISSUE THREAD

**Issue by Napster653** [Foxlider/FASTER#102]
**Is your feature request related to a problem? Please describe.**  
The list of profiles on the left side is not scrollable. This means that the number of profiles we can use is limited.

![image](https://user-images.githubusercontent.com/32395467/219864509-385feecc-8912-4128-a222-c679a5ae1a31.png)

**Describe the solution you'd like**  
Could you make this panel scrollable?

**Describe alternatives you've considered**  
Currently, we have to manually edit the user.config xml content to manage our profiles.

**Additional context**
-

**Comment by Foxlider** [comment]
Daaaaayum that's a lot of profiles !
One option is to make the window bigger but it's not scrollable for now

**Comment by Napster653** [comment]
> Daaaaayum that's a lot of profiles ! One option is to make the window bigger but it's not scrollable for now

I don't understand, are we using the application wrong? We started using FASTER because it lets us have one profile per mission with its own modset but you make it sound like having many profiles is not the intended use case.

Is there an alternative way to do this that I'm missing? We currently have 506 different missions, each with their own modset.

**Comment by Shadblade5** [comment]
> Is there an alternative way to do this that I'm missing? We currently have 506 different missions, each with their own modset.

There isn't a real reason to have a ton of profiles unless you have different addon options or difficulty settings per mission. Generally I can get away with using less than 3 with just swapping modpack and the mission.

**Comment by Napster653** [comment]
@Shadblade5 Thank you for your answer. I feel like I'm not understanding something obvious.

Each of our missions has a different modset, so if we had 3 profiles it would mean that whenever we have to launch a mission we would have to go through the list of 104 mods ticking checkboxes. That's a lot of work that we'd rather do just once.

Wouldn't it just make more sense if each mission had its own profile? Is there some way to choose a modset other than ticking the checkboxes that I'm completely missing?

**Comment by Shadblade5** [comment]
You can use the HTML Export function in the arma launcher to create a modpack that is importable

**Comment by Foxlider** [comment]
The intended use of different profile is when you have very different modpacks or when you need to launch multiple servers at the same time.

It is recommended to use the [Load From File](https://github.com/Foxlider/FASTER/wiki/Profile-Page#profile-settings) in your profile to select all the required mods.

**Comment by Napster653** [comment]
I'll give that a try, although we download mods from the workshop and host them on our ftp as local mods so we can update them on our own schedule so I don't know how well that will work with a lot of local mods.
