### ISSUE TITLE
[BUG] Can't update anything

### ISSUE THREAD

**Issue by CALADARI** [Foxlider/FASTER#106]
**Describe the bug**  
Returns 403 error when I try to update the game or any mod. Issue starts to bothering me probabaly after the recent SteamCMD update.

Connecting to Steam as [MySteamName]
Please enter your 2FA code: 
Retrying... 
Connected !
Fetching mod 2912941775 infos... 
Error: Could not download the manifest = 4655203158023421184 after 5 attempts. Inner Exception: Response status code does not indicate success: 403 (Forbidden).

Connecting to Steam as [MySteamName]
Please enter your 2FA code: 
Retrying... 
Connected !
Fetching mod 2876540929 infos... 
Error: Could not download the manifest = 470305719858119684 after 5 attempts. Inner Exception: Response status code does not indicate success: 403 (Forbidden).

Starting Update...
Please don't quit this page or cancel the download
This might take a while...
Checking Shared Content...
Checking Executables...
Checking Arma 3 Server Creator DLC - GM...
Checking Arma 3 Server Creator DLC - SOGPF...
Checking Arma 3 Server Creator DLC - Western Sahara...
Connecting to Steam as [MySteamName]
Please enter your 2FA code: 
Retrying... 
Connected !
Attempting to start download of app 233780, depot 233781  (1/5)... 
Error: Could not download the manifest = 6240918786341720341 after 5 attempts. Inner Exception: Response status code does not indicate success: 403 (Forbidden).

All Done ! 

**To Reproduce**  
Steps to reproduce the behaviour:
1.Update the game or any mod
2. See error

**Screenshots**  
![屏幕截图_20230409_141214](https://user-images.githubusercontent.com/45614593/230757640-2d3f8449-cc13-4e49-8274-f31cb356e9be.png)
![屏幕截图 2023-04-09 144542](https://user-images.githubusercontent.com/45614593/230758682-7e1a8519-34c7-4779-88e9-ad5865ea5cc0.png)

**OS Version (required):**  
 - OS: Microsoft Windows Server 2019 Datacenter 10.0.17763 
 - FASTER Version 1.8f

**Additional context**  
403 error only apply to FASTER, by manually using steamCMD no issue.(See screenshot above.)

**Comment by CALADARI** [comment]
If someone who has a temporary fix (e.g. manually use steamCMD command to update these, so far I know is check the vanilla server; manually download mod files and ctrl+X to 'update'.) please do reply to me, I owe you a big appreciation.

**Comment by satanahell** [comment]
Hello,

Got the same issue 2 days ago just after swapping to a dedicated steam account. I swap back to the original account (mine) and all was fine again. Got no time to figure out why at the moment, it may be a kind of brand new steam account limitation ...

**Comment by CALADARI** [comment]
> Hello,
> 
> Got the same issue 2 days ago just after swapping to a dedicated steam account. I swap back to the original account (mine) and all was fine again. Got no time to figure out why at the moment, it may be a kind of brand new steam account limitation ...

I've been consistently using same account , but anyway I'll try swap account to see if it solve the issue. Will update my result later.
Thx for provinding this lead!

**Comment by satanahell** [comment]
One more point, i just tested one account which didn't own ARMA3 game and i'm not able to access to the mod repository on steam ... Be sure the account you'r using own the arma 3 game.

**Comment by Foxlider** [comment]
Are you sure you are using the latest version ? Steam fucked up some things with their API and manifests could not be retrieved

**Comment by satanahell** [comment]
Faster version 1.8f for me, tested on 3 different server, same behavior if the steam acount used didn't own arma 3.

**Comment by Foxlider** [comment]
The account MUST own arma3 or it won't work correctly and Steam's API might reject your request. 

I noticed a bug in the login procedure that caused the credentials to stay the same after a failed connexion even if you changed them. This requires you to restart the app for the login change to take effect.

**Comment by CALADARI** [comment]
> The account MUST own arma3 or it won't work correctly and Steam's API might reject your request.
The account which have the issue DO own Arma3 as it is my own account. FASTER ver 1.8f, I haven't test out switch account cuz recent final exam.
But I do wan't to provide a supplmentary info, my FASTER now consistantly ask me for 2FA code EVERY login. could be the 
> I noticed a bug in the login procedure that caused the credentials to stay the same after a failed connexion even if you changed them. This requires you to restart the app for the login change to take effect.
I dont remember that happends before this 403 forbidden issule occurs to me. Maybe what I need to do is just reset FASTER's credentical chace?

**Comment by CALADARI** [comment]
New error : `Failed! Error: The client cannot be used anymore as it was disposed. Create a new client for further work.`

**Comment by CALADARI** [comment]
No solution fond, to anyone who have same trouble as me. I use steamCMD & hardfolderlink for a old-school server management. 
look the depot ID and manifest id up in steamDB or any place you prefer, use download_depot to download cDLC files, then use mklink or third-party plugin to create syslink to allow you mount em.
![image](https://user-images.githubusercontent.com/45614593/236192126-c19a9a56-de7f-4453-90af-8eeff01f04c8.png)

**Comment by Foxlider** [comment]
Nothing came up so far in the investigation.
Everything works fine with latest version on all my devices.
I'll try to investigate further

**Comment by CALADARI** [comment]
i just look up into some steam documents. and found these.

`Every request to this host must be made with your publisher Web API key, even requests which would ordinarily not need any key. Requests made without a valid publisher key will return a 403 error code.`

`Requests generating 403 status codes, which typically happens when using a regular Web API key instead of your publisher key, will incur strict rate limits for the connecting IP. This is in an effort to ensure high availability.
`
could it be related?

**Comment by CALADARI** [comment]
Well, turns out to be domestic network issue. Somehow steamwebAPI was blocked in my region, so turns out to be it is not actually 403 forbidden, its simply timed-out issue.
403 forbidden doesn't have to mean smth with either steam or FASTER, it can also indicates a timed-out between you and the Web API, use proxy to slove the issue.Case closed.

最近国内可能是加强了对steam web API的屏蔽，如果你和我一样遇到了403forbidden的报错，可能只是单纯的链接不上下载服务器。解决办法是直接挂个梯子，case closed.
