### ISSUE TITLE
[FEATURE] whitelist option to allow optional clients side mods on keyed servers

### ISSUE THREAD

**Issue by entrippy** [Foxlider/FASTER#107]
**Is your feature request related to a problem? Please describe.**  
My Arma server requires mod signing to prevent unwanted client side mods (like personal arsenal).
I wish to allow players to optionally use a known selection of other client side mods should they desire. 
This is usually achived by adding the client side mod key to the keys directory, but not declaring it as a required client side mod in config.

FASTER does not seem to allow this approach in its current design. Keys for clientside mods that aren't ticked as client in the profile are not copied to the keys directory, and once ticked, the key is copied but now all users are forced to use this mod.

**Describe the solution you'd like**  
Along with "Server", "Client", and "HC", categories that force mod use, add a "Whitelist" category column that allows keys to be copied into the keys folder by FASTER without requiring Server, Client, or HC use them

**Describe alternatives you've considered**  
To work around this I have to manually copy the key into the keys folder. This workaround often needs to be repeated as mods etc are updated. Also as the list of mods I wish to whitelist grows, the manual workaround does not scale.

**Additional context**

**Comment by MildlyInterested** [comment]
https://github.com/Foxlider/FASTER/pull/95
