### ISSUE TITLE
"Access to depot denied" when trying to download mods

### ISSUE THREAD

**Issue by jack-cole** [Foxlider/FASTER#113]
**Describe the bug**  
When trying to update the mods, every mod has this error (with different ids and codes):

```
Starting 2522638637
Getting manifest for 2522638637
Error: One or more errors occurred. (Access to depot id = 107410 denied.) Inner Exception: Access to depot id = 107410 denied.
Download 2522638637 completed, it took 0m 0s 649ms
Thread 2522638637 complete  (7 / 45)
```

All the mod folders are empty. I was able to download the game server just fine, so my login is working.

**OS Version (required):**  
 - OS: Windows Server 2022
 - FASTER Version 1.9b

**Comment by MildlyInterested** [comment]
Your steam account needs to own Arma 3 to download mods. Mentioned here: https://github.com/Foxlider/FASTER/wiki/Setup-Guide-(1.8)#first-launch and here https://github.com/Foxlider/FASTER/wiki/Steam-Updater-Page

**Comment by jack-cole** [comment]
Thank you @MildlyInterested, using my personal steam account solved the problem.
