### ISSUE TITLE
[BUG] Client is faulted and cannot be used: Error code: TryAnotherCM

### ISSUE THREAD

**Issue by ViVi141** [Foxlider/FASTER#114]
**Describe the bug**  
 i try to download and update arma3 server
 this bug make me cannot download or update anything

**To Reproduce**  
Steps to reproduce the behaviour:
1. Go to Main\updater\ arma 3 settings 
2. Click on 'update'
3. Starting Update...
Please don't quit this page or cancel the download
This might take a while...
Checking Shared Content...
Checking Executables...
Checking Arma 3 Server Creator DLC - SOGPF...
Connecting to Steam as vivi14141
Failed! Error: Client is faulted and cannot be used: Error code: TryAnotherCM

All Done ! 

**Expected behaviour**  
just download and update

**Actual behaviour**  
this bug happen anything about download and update , mod and arma3 server

**OS Version (required):**  
 - OS: Windows Server 2022 Datacenter 21H1
 - FASTER Version [1.9b]

**Additional context**  
i miss my steamcmd ,because  i use 1.7 version ,download  is ok, but 1.8&1.9,i usually cannot download or update something

**Comment by metoli315** [comment]
I have had the same problem today the fix is just reset the FASTER and then do not fill in the username and password so it can login anonymous so it won't have the same problem.

**Comment by mwpowellhtx** [comment]
Running into this today, latest version AFAIK. What was the resolution again?
