### ISSUE TITLE
[BUG] Steam Client API Expired

### ISSUE THREAD

**Issue by GreatGhaleon** [Foxlider/FASTER#119]
**Describe the bug**  
When attempting to update the server or mods, the error 'Client is faulted and cannot be used' is reported.

**To Reproduce**  
Steps to reproduce the behaviour:
1. Open FASTER
2. Attempt to update any component.
3. Observe the following error in the console: Connecting to Steam as [username redacted]
Failed! Error: Client is faulted and cannot be used: Error code: Expired

**Expected behaviour**  
The server or mod should update.

**Actual behaviour**  
The server or mod does not update. 

**Screenshots**  
Screenshot would not be useful in this case.

**OS Version (required):**  
 - OS: Windows Server 2019
 - FASTER Version: 1.9b released June 4th

**Additional context**

**Comment by GreatGhaleon** [comment]
Looks like this is resolved by deleting the sentries folder

**Comment by Foxlider** [comment]
Marking as resolved
