### ISSUE TITLE
[FEATURE] Add Creator DLC "Spearhead 44" download option

### ISSUE THREAD

**Issue by swebow** [Foxlider/FASTER#125]
**Is your feature request related to a problem? Please describe.**  
Today (07/25) the creator DLC "Spearhead 44" got released.

**Describe the solution you'd like**  
I wish to have FASTER add the checkbox for Spearhead 44 like the other creator DLCs.

**Describe alternatives you've considered**  
It possible to manually download it via SteamCMD but not via FASTER.

**Additional context**  
Link to said DLC - https://store.steampowered.com/app/1175380/Arma_3_Creator_DLC_Spearhead_1944/

**Comment by Foxlider** [comment]
Fixed with latest version of FASTER
