### ISSUE TITLE
[FEATURE] Custom Workshop Folder Location

### ISSUE THREAD

**Issue by vigilvindex** [Foxlider/FASTER#13]
Add the ability to manually specify the steam workshop addon folder location for when it cannot be found.

**Comment by Foxlider** [comment]
Have you tried adding as local mods folder ?

**Comment by vigilvindex** [comment]
> Have you tried adding as local mods folder ?

I tried that first and it worked, but I thought it wasn't they way it is intended to work. So I set the steam install to the steam library location where I have Arma installed is, rather than the default steam client install location and it picked up the workshop files as it normally would. In steam client from the file menu, Steam, Settings, Downloads, there is Steam Library Folders, in there I am a few split over SSD drives etc so I think this where the initial problem of not finding the workshop folder came from.

**Comment by Foxlider** [comment]
Well first of all, FASTER should not be on a "client" system but on a server. It might fuck up some things if not set up properly.
Secondly, FASTER is not supposed to work with Steam. It can but its has its quirks to make it work. 

The ideal configuration is to have it loaded on it's own server, with its own arma install and SteamCMD.
