### ISSUE TITLE
[BUG] Error on server and DLC update

### ISSUE THREAD

**Issue by TheWolek** [Foxlider/FASTER#143]
Im trying to update the server and SOG DLC, because on mission load im getting an error "Vehicle class X no longer exists".
I have put my user name and password and selected Profiling and also SOG DLC checkbox.
After clicking on the Update button im getting an error:

```
Starting Update...
Please don't quit this page or cancel the download
This might take a while...
Checking Shared Content...
Checking Executables...
Checking Arma 3 Server Creator DLC - SOGPF...
Connecting to Steam as wolek1231
Please enter your 2FA code: 
Retrying... 
Connected !
Error: Value cannot be null. (Parameter 's')

All Done ! 
```

What parameters am i missing?
![image](https://github.com/Foxlider/FASTER/assets/16455121/ac69a56c-7f88-4378-849d-b697cb0f9755)

**Comment by MildlyInterested** [comment]
Your FASTER is out of date.

**Comment by PulsarNeutronStar** [comment]
you should be able to update via Others/Settings
