### ISSUE TITLE
Difficulty Preset

### ISSUE THREAD

**Issue by MontyBravo** [Foxlider/FASTER#15]
The Difficulty Preset setting in the Missions tab does not appear to force difficulty on the mission selection screen?

**to reproduce**
Set difficulty Preset to 'Custom' join the server, pick a mission, difficulty options are available.

**Expected behavior**
Correct me if I am wrong, but I thought the setting was meant to create the forcedDifficulty = "<difficultyClass>"; value in the server.cfg

**Actual behavior**
No value created, does not appear to do anything, note I am using it without choosing missions in the mission selector override.

**Screenshots**
![image](https://user-images.githubusercontent.com/20632267/98425402-06e3e700-20e9-11eb-8e7a-33d81ad4019b.png)

**OS Version (required):**
 - OS: Windows 10
 - Version  1.7a

**Comment by Foxlider** [comment]
FASTER does not set the forced difficulty. It sets the difficulty per mission
