### ISSUE TITLE
[BUG] DLC Update - "No manifest could be found that matches all specified criteria."

### ISSUE THREAD

**Issue by SimpkinSlice** [Foxlider/FASTER#150]
**Describe the bug**  
Attempting to update DLC results in Error: No manifest could be found that matches all specified criteria.

**To Reproduce**  
Steps to reproduce the behaviour:
1. Go to Updater
2. Enable all DLC (although most DLC seem to do individually it as well)
4. Click update
5. See error No manifest could be found that matches all specified criteria.

**Expected behaviour**  
DLC to update.

**Actual behaviour**  
Update cancels complaining of no depot.

**OS Version (required):**  
 - OS: Windows Server
 - FASTER Version [e.g. 1.9d]

**Additional context**  
Updating SPE at first 

Update log:

```
Starting Update...
Please don't quit this page or cancel the download
This might take a while...
Checking Shared Content...
Checking Executables...
Checking Arma 3 Server Creator DLC - GM...
Checking Arma 3 Server Creator DLC - CSLA...
Checking Arma 3 Server Creator DLC - SOGPF...
Checking Arma 3 Server Creator DLC - Western Sahara...
Checking Arma 3 Server Creator DLC - SPE...
Connected !

Fetching informations of app 233780, depot 233781 from Steam (1/7)... 
OK.
Downloading 0 files with total size of    0.00  B...
Verifying Install...
Progress 100.00%
Progress 100.00%
Progress 100.00%
Progress 100.00%
Progress 100.00%
Verification completed, 0 files queued for download. (0 bytes)
Download completed
Progress 100.00%
Skipping Download...

Fetching informations of app 233780, depot 233782 from Steam (2/7)... 
OK.
Downloading 0 files with total size of    0.00  B...
Verifying Install...
Verification completed, 0 files queued for download. (0 bytes)
Download completed
Progress 100.00%
Skipping Download...

Fetching informations of app 233780, depot 233787 from Steam (3/7)... 
OK.
Download completed
Downloading 0 files with total size of    0.00  B...
Verifying Install...
Error: No manifest could be found that matches all specified criteria.


```

**Comment by PulsarNeutronStar** [comment]
is this with profiling branch?

**Comment by SimpkinSlice** [comment]
> is this with profiling branch?

Did it on both variants

**Comment by SimpkinSlice** [comment]
> When setting up the server for the first time, you can get issues if you initially update/download the server files directly as profiling branch. I dont know if this is related to your issue but I suggest you do the following:
> 
>     1. Inital download of the serverfiles in as non-Profiling.
> 
>     2. Update the serverfiles with all (needed) DLCs.
> 
>     3. Update the serverfiles to the Profiling branch.

Don't think so, issue suddenly came up this week while double checking server files were up to date ahead of the weekend (non-profiling), only switched to profiling to check it did the same thing on that (it did)

**Comment by SimpkinSlice** [comment]
> > I also have this problem
> 
> @Sinakawa
> 
>     1. can you go through your DLC list one by one and see which ones you have issues with.
> 
>     2. Has this only recently happened or been going on for awhile.
> 
>     3. Is this a fresh install.
> 
> 
> Plus as Pulsar said above:
> 
> > When setting up the server for the first time, you can get issues if you initially update/download the server files directly as profiling branch. I don't know if this is related to your issue but I suggest you do the following:
> > ```
> > 1. Initial download of the server files in as non-Profiling.
> > 
> > 2. Update the server files with all (needed) DLCs.
> > 
> > 3. Update the server files to the Profiling branch.
> > ```

Updating each individually (non-profiling):
No DLC - Good for both
Contact - Good for both
GM - Good for all 3
SOG - [Error: No manifest could be found that matches all specified criteria.] after finishing 2/3 (depot 233782)
CSLA - [Error: No manifest could be found that matches all specified criteria.] after finishing 2/3 (depot 233782)
WS - [Error: No manifest could be found that matches all specified criteria.] after finishing 2/3 (depot 233782)
SPE - Good for all 3

**Comment by Sinakawa** [comment]
> > When setting up the server for the first time, you can get issues if you initially update/download the server files directly as profiling branch. I dont know if this is related to your issue but I suggest you do the following:
> > ```
> > 1. Inital download of the serverfiles in as non-Profiling.
> > 
> > 2. Update the serverfiles with all (needed) DLCs.
> > 
> > 3. Update the serverfiles to the Profiling branch.
> > ```
> 
> Don't think so, issue suddenly came up this week while double checking server files were up to date ahead of the weekend (non-profiling), only switched to profiling to check it did the same thing on that (it did)

It didn't help me either.




> > > I also have this problem
> > 
> > 
> > @Sinakawa
> > ```
> > 1. can you go through your DLC list one by one and see which ones you have issues with.
> > 
> > 2. Has this only recently happened or been going on for awhile.
> > 
> > 3. Is this a fresh install.
> > ```
> > 
> > 
> > Plus as Pulsar said above:
> > > When setting up the server for the first time, you can get issues if you initially update/download the server files directly as profiling branch. I don't know if this is related to your issue but I suggest you do the following:
> > > ```
> > > 1. Initial download of the server files in as non-Profiling.
> > > 
> > > 2. Update the server files with all (needed) DLCs.
> > > 
> > > 3. Update the server files to the Profiling branch.
> > > ```
> 
> Updating each individually (non-profiling): No DLC - Good for both Contact - Good for both GM - Good for all 3 SOG - [Error: No manifest could be found that matches all specified criteria.] after finishing 2/3 (depot 233782) CSLA - [Error: No manifest could be found that matches all specified criteria.] after finishing 2/3 (depot 233782) WS - [Error: No manifest could be found that matches all specified criteria.] after finishing 2/3 (depot 233782) SPE - Good for all 3

confirm, I have the same error, for the same dlc, at the same stage..

**Comment by MildlyInterested** [comment]
sounds like steam or someone adjusted depot numbers again

**Comment by jupster** [comment]
Issue resolved on master
