### ISSUE TITLE
[BUG] Copies all *.bikey in mod folder, including unspecified optionals

### ISSUE THREAD

**Issue by MildlyInterested** [Foxlider/FASTER#151]
**Describe the bug**  
Have `@ace` as a deployed mod, copy keys, there is no .bikey files for noactionmenu etc in the servers key folder.

**To Reproduce**  
Steps to reproduce the behaviour:
1. Deploy ace mod and copy keys profile
2. Check server key folder, contains optional bikey files

**Expected behaviour**  
Do not copy additional bikey files.

**Actual behaviour**  
Seems like its searching for any bikey file in the mod folder and copies them all over.

**Additional context**  
ACEs optionals structure looks like this:
`@ace\optionals\@ace_noactionmenu\keys\*.bikey`
The main key is located here:
`@ace\keys\*.bikey`
I suggest limiting how many folders deep the search for .bikey files is, the main key should not be as deep as optionals.

**Comment by PulsarNeutronStar** [comment]
![image-1](https://github.com/Foxlider/FASTER/assets/56258612/4199c88e-52e9-4899-a06e-b61834d3745a)
https://cdn.discordapp.com/attachments/602087483370635266/1164478373129637909/image.png?ex=65435bff&is=6530e6ff&hm=fd062dc69c824c9c55120c597963faa8b80bbcf03e5fd1cbc599cacbd63f58a5&

**Comment by PulsarNeutronStar** [comment]
![image-4](https://github.com/Foxlider/FASTER/assets/56258612/11aaf4ba-c62e-4428-8cf2-37b100f6050a)

**Comment by MildlyInterested** [comment]
If someone needss these keys they still need to get the client to actually load these PBOs, which is not possible with the official ACE steam mod unless you move folders around manually. Chances of that happening are really low. 

If someone want's players to load e.g. ACE_Particles these players will need to subscribe to an ACE_Particles mod, they server can do the same and load the .bikey from there. Bikey in there won't be two folders deep.

**Comment by jupster** [comment]
For when i fix this -> https://github.com/Foxlider/FASTER/blob/f4492316393656b8f5fe591d1ed7f2cd1cdf99ad/FASTER/ViewModel/ProfileViewModel.cs#L367C13-L367C13

**Comment by liamcannon** [comment]
😎 @jupster
