### ISSUE TITLE
How to install mods?

### ISSUE THREAD

**Issue by ZERONIGT** [Foxlider/FASTER#157]
I've encountered the following problem: when installing mods, they don't load. So I want to ask if there is any guide to this?

**Comment by MiszczuZPolski** [comment]
https://github.com/Foxlider/FASTER/wiki

**Comment by ZERONIGT** [comment]
> https://github.com/Foxlider/FASTER/wiki

I tried but did not understand how to add additionals mods

**Comment by ZERONIGT** [comment]
And for some reason the mods are not signed....

**Comment by ZERONIGT** [comment]
![image](https://github.com/Foxlider/FASTER/assets/78171863/477db3ec-a3b8-4ae1-8185-eeea7a45813f)

**Comment by PulsarNeutronStar** [comment]
https://github.com/Foxlider/FASTER/wiki/FAQ#faster-says-my-mods-are-up-to-date-but-the-folder-is-emptyserver-complains-about-missing-addons

Did you deploy the mods and copy the keys?
https://github.com/Foxlider/FASTER/wiki/Setup-Guide-(1.8)

**Comment by ZERONIGT** [comment]
> https://github.com/Foxlider/FASTER/wiki/FAQ#faster-says-my-mods-are-up-to-date-but-the-folder-is-emptyserver-complains-about-missing-addons
> 
> Did you deploy the mods and copy the keys? https://github.com/Foxlider/FASTER/wiki/Setup-Guide-(1.8)

Well, then how do I do it? 
![image](https://github.com/Foxlider/FASTER/assets/78171863/d612eced-32f0-4001-a12a-4b179e914c8d)
Do you mean that it is not necessary to download the mod and run it exclusively on the client?
