### ISSUE TITLE
Add the ability to edit voting on the server or disable it

### ISSUE THREAD

**Issue by ZERONIGT** [Foxlider/FASTER#158]
I faced the need to disable voting for the administrator, but I did not find this function in the program, so I had to register it manually

**Comment by PulsarNeutronStar** [comment]
Further: your manual edits in the generated server.cfg will be overwritten the moment you are saving the server profile in faster

**Comment by ZERONIGT** [comment]
Yes, but I need a vote for the kick

**Comment by ZERONIGT** [comment]
And another question about enabling advanced flight. How do I enable it here?

**Comment by jupster** [comment]
> Yes, but I need a vote for the kick
> 
> 

As said above

>https://community.bistudio.com/wiki/Arma_3:_Mission_Voting has the information you need to customize voting options. 
>
>

So you can utilise the mission override (ref photo) to tune the voting to how you want it.

![grafik](https://github.com/Foxlider/FASTER/assets/56258612/f608d0c6-4bc3-4d8d-9583-50d63110a313)

**Comment by jupster** [comment]
> And another question about enabling advanced flight. How do I enable it here?

If your wanting it for the entire server then you can utilise

```
forceRotorLibSimulation = 0;  To disable

forceRotorLibSimulation = 1;  To enable
```

**Comment by jupster** [comment]
If you have any more questions regarding this I'd suggest utilising the FASTER discord


https://discord.gg/2BUuZa3

**Comment by PulsarNeutronStar** [comment]
also https://github.com/Foxlider/FASTER/pull/149  plus https://github.com/Foxlider/FASTER/issues/38
