### ISSUE TITLE
Blurred text after update from 1.98.146.303 to 2.00.146773

### ISSUE THREAD

**Issue by evandrix** [Foxlider/FASTER#16]
![screenshot](https://user-images.githubusercontent.com/169669/98890066-2064a480-24d6-11eb-8c93-723297967c29.png)

**Comment by Foxlider** [comment]
Not a FASTER issue.

You used FASTER to update a client version of Arma3. FASTER uses Server versions.
Server versions are not meant to be launched like that, they are servers.
You probably corrupted your install

**Comment by evandrix** [comment]
oh okay, thanks for clarifying.
