### ISSUE TITLE
[BUG] If I add A Mod the Server has 0/0 Slots

### ISSUE THREAD

**Issue by xuynix** [Foxlider/FASTER#160]

**Comment by jupster** [comment]
> Maximum Players Have Been Reached
Usually an issue when the Mission File requires a Mod that isnt loaded on the server and the mission is being auto-loaded during server start up.
You'll see the server to have 0/0 Slots in the server list.

Very often its a missing terrain mod on the server, but it could also be that the Player Slot Units/Objects are missing.

Server RPT will assist with finding the issue.

**Comment by MIlanMCreator** [comment]
Play Slot Units are fine I tested it in editor and it worked fine I
 had my 16 slots

**Comment by MIlanMCreator** [comment]
And my FASTER isnt Deploying the mods correctly in the server folder after deploying I just get a folder named @ it doesnt create 
the @450814997 folder

**Comment by jupster** [comment]
This sounds likely a user error issue. 

Please join the discord https://discord.gg/2BUuZa3 for much easier support

**Comment by PulsarNeutronStar** [comment]
As jupster said, that is not a faster bug, but an error regarding setup.

Also, if the mods are not deployed then yea, the server wont be able to use any of the mods, causing the 0/0 slots issue.
