### ISSUE TITLE
[BUG] MODS - Server client - Bad Phrasing

### ISSUE THREAD

**Issue by OverlordZorn** [Foxlider/FASTER#164]
@jupster 
In the current state, the `Profile/Mods/` Table has the collumn `Server` and `Client` which are reffering to the `-server="..."` and `-mods="..."` Parameters. 

As of now, they are **massively missleading** for anyone who is not already familiar with those parameters.

![grafik](https://github.com/Foxlider/FASTER/assets/56258612/06c0a1d9-abad-4119-a2a8-c2532bc2455f)

PLEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWWWSEEEEEEE FIX

The following Mockup shows a way to make it so much more intuitive even for the common pleb who doesnt know what he is doing.
`Only Server` & `Client + Server`

![faster-mockup](https://github.com/Foxlider/FASTER/assets/56258612/45814efe-b236-46bc-82b0-e9d1b2f22172)

**Comment by PulsarNeutronStar** [comment]
Alternativ: Disclaimer/Explainer in the empty area on the left.

![grafik](https://github.com/Foxlider/FASTER/assets/56258612/6027176e-1194-48ec-8e23-a157af2c4e22)

**Comment by Foxlider** [comment]
![](https://akm-img-a-in.tosshub.com/indiatoday/images/story/202106/cover4_new_1200x768.jpeg)

It's all in the wiki
Always has been
https://github.com/Foxlider/FASTER/wiki/Profile-Page#mods

**Comment by PulsarNeutronStar** [comment]
> ![](https://camo.githubusercontent.com/454905b8621ff28f94ee027e751f1395665fe0ae93493bcd5cb2d9b496e71d04/68747470733a2f2f616b6d2d696d672d612d696e2e746f73736875622e636f6d2f696e646961746f6461792f696d616765732f73746f72792f3230323130362f636f766572345f6e65775f31323030783736382e6a706567)
> 
> It's all in the wiki Always has been https://github.com/Foxlider/FASTER/wiki/Profile-Page#mods
> 
> Those edits add clutter to an already overloaded UI

Wiki doesnt help. People one the discord come again and again with both coloumn selected. 
The current wording is missleading.
