### ISSUE TITLE
[FEATURE] Adding Reaction Force to the DLC checklist

### ISSUE THREAD

**Issue by Bacon8tor** [Foxlider/FASTER#173]
**Is your feature request related to a problem? Please describe.**  
New Reaction Force came out and want to be able to add it 

**Describe the solution you'd like**  
Adding the Creator DLC Reactionforce to the list of DLC so it can be downloaded
**Describe alternatives you've considered**  
manually using steam cmd or coping the folder manually.
**Additional context**

**Comment by PulsarNeutronStar** [comment]
There's a "beta" built that has that already.

**Comment by PulsarNeutronStar** [comment]
https://github.com/jupster/FASTER1.9/releases/tag/1.9d_145.5
it is based off the feature branch

**Comment by PulsarNeutronStar** [comment]
Did some testing earlier today and have a server running on this version.

the verison mentioned above will soon be merged into stable once testing concludes no issues and the authors are actually awake :D

**Comment by jupster** [comment]
Will be doing testing in roughly 30. As said above feel free to use the beta until it is merged.

**Comment by jupster** [comment]
Merged just now
