### ISSUE TITLE
[BUG] Forced Difficulty Dropdown goes to the wrong place

### ISSUE THREAD

**Issue by OverlordZorn** [Foxlider/FASTER#177]
RF beta.

https://streamable.com/08v6g9

The Drop-Down Menu on Fasters
FASTERPROFILE >> Missions >> Difficutly Settings >> DropDown "Forced Difficulty"

controls a line in the arma3profile file.
> forcedDifficulty = 3;	// Forced difficulty (0 = Recruit, 1 = Regular, 2 = Veteran, 3 = Custom)

I have not found anywhere a reference that this is the right place.

instead, it might need to change a line in the server.cfg

`forcedDifficulty = "Custom"; //Forces the custom Difficulty in Profile.Arma3Profile`

![grafik](https://github.com/Foxlider/FASTER/assets/56258612/26b9a71f-5ddb-4bed-b734-0aca46befe84)
https://community.bistudio.com/wiki/Arma_3:_Server_Config_File#Arma_3_-_Forced_difficulty

**Comment by PulsarNeutronStar** [comment]
![grafik](https://github.com/Foxlider/FASTER/assets/56258612/96cd5657-4153-4caa-8f3a-eb500c77bd03)

server 3.1 runs forced Difficulty via server.cfg and it is effective.
server 3.2 runs forced difficulty only via dropdown, it is not effective.

**Comment by jupster** [comment]
Back home so will try and get this fixed this week
