### ISSUE TITLE
"Server version request timed out"

### ISSUE THREAD

**Issue by therealsputnik** [Foxlider/FASTER#178]
Running the Exile.Altis pbo, everything seems to be working.  Server shows up in the server browser, server is up and headless client connected, but when I try to connect from a different PC I get:

Receiving server version...
Server version request timed out"

On the loading screen, bottom left.  Eventually it times out and I'm disconnected.  Back to server browser window.

I have tried disabling signature checking and battleye, just in case, but does not seem to have any effect.

 - Windows 10 Dedicated Computer
 - FASTER Version 1.9d

**Comment by jupster** [comment]
I don't believe FASTER is dealing with said "server version". @Foxlider might have some better insight in this.

You might be best off checking in with exile  devs on this issue.

**Comment by Foxlider** [comment]
That's true

This is an Arma issue, not FASTER

**Comment by therealsputnik** [comment]
Noted. Thank you.

**Comment by therealsputnik** [comment]
Closed
