### ISSUE TITLE
[BUG] v1.9e unable to properly import server profiles from v1.9d

### ISSUE THREAD

**Issue by Drift91** [Foxlider/FASTER#185]
**Describe the bug**  
It seems that v1.9e will load the profiles from v1.9d upon first launch and display them in the UI, but won't actually write them to the XML config file. I was able to reproduce this with a fresh v1.9d config with a single fresh server profile added, otherwise I'd provide my config file. Manually copying the `ArrayOfServerProfile` block into the new v1.9e config produces the same behaviour; It displays the profiles, but then upon the next launch they're gone because they got wiped from the config file on the first launch.

**To Reproduce**  
Steps to reproduce the behaviour:
1. Wipe all config files from `%localappdata%\FoxliCorp\`.
2. Launch v1.9d and create a server profile, then close the app.
3. Launch v1.9e and observe the profile is still present.
4. Close and relaunch v1.9e, the profile is now gone.

**Expected behaviour**  
For the imported profiles to remain after closing and relaunching v1.9e.

**Actual behaviour**  
Any profiles imported from v1.9d get wiped upon closing and relaunching v1.9e.

**Screenshots**  
N/A

**OS Version (required):**  
 - OS: [Windows Server 2022 Standard (21H2)]
 - FASTER Version [1.9e]

**Additional context**  
It's probably already obvious, but any profiles made in v1.9e seem to remain. Although I haven't tested by mixing v1.9d and v1.9e profiles together at once.

**Comment by jupster** [comment]
An issue with the change in Tactical ping added in 1.9e. 

This seems to be working: https://github.com/Foxlider/FASTER/wiki/HowTo:-Restore-Faster-after-update

I'm in the process of making sure they are compatible but have been really busy so just haven't gotten to that yet

**Comment by Drift91** [comment]
Thanks, that seems to have worked. The wording of the wiki entry might need to be changed though, as at first I thought it needed to be set before closing 1.9d and was confused as to what needed to be changed as it was already at 'enabled'.

**Comment by jupster** [comment]
> Thanks, that seems to have worked. The wording of the wiki entry might need to be changed though, as at first I thought it needed to be set before closing 1.9d and was confused as to what needed to be changed as it was already at 'enabled'.

Will look into rewording it. Thanks for the input
