### ISSUE TITLE
[FEATURE] Relocate DLC Drop-Down in Profile Section

### ISSUE THREAD

**Issue by OverlordZorn** [Foxlider/FASTER#193]
![image](https://github.com/user-attachments/assets/2506c28c-c346-4e7e-ae3d-ba0d1b0c7ed3)
I constantly forget to check the enabled DLC when setting up Server Profiles in Faster cause its hidden in here and every now and then, its causing delays during our events.

I would like to ask if its possible to relocate it to the left, so its always visible - there is more then enough space over there.

**Comment by OverlordZorn** [comment]
@jupster AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by jupster** [comment]
Shouldn't be too hard to do. I think it would be a good idea to make it easier.

**Comment by liamcannon** [comment]
I'll do this.
