### ISSUE TITLE
[BUG] Crash on 2fa screen after cancelling mod updates

### ISSUE THREAD

**Issue by WolfSkin0** [Foxlider/FASTER#2]
**Describe the bug**
FASTER crashes when you start an update, press cancel before the 2fa screen comes up and then press submit.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a mod update
2. Click cancel before the 2fa popup comes up
3. Leave the 2fa popup empty and press submit

**Expected behaviour**
The 2fa box to close and nothing further to happen

**Actual behaviour**
The entire application crashes

**Screenshots**
N/A

**OS Version (required):**
 - OS: Windows Server 2019 Standard
 - Version: 17763.rs5_release.180914-1434

**Comment by Foxlider** [comment]
This will finally be fixed on next update !
