### ISSUE TITLE
[BUG] Steam Mods table sorting do not respect filesize units

### ISSUE THREAD

**Issue by makarov-roman** [Foxlider/FASTER#20]
**Describe the bug**
Currently it sorts based on digits without respect to units. E.g. 1050KB > 30GB

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Steam Mods'
2. Click on 'Size'
3. Sorting is not correct

**Screenshots**
![изображение](https://user-images.githubusercontent.com/11902307/106064297-ab832d00-610a-11eb-95c6-0057ff27afab.png)

**OS Version (required):**
 - OS: [e.g. Windows 10 20H2 Home]
 - Version [e.g. 1.7a]

**Comment by Foxlider** [comment]
Known bug, should be fixed in next big update with the mod system rework

**Comment by makarov-roman** [comment]
Good to know! Should I close the issue?
