### ISSUE TITLE
[FEATURE] Add (De)Select All buttons for server mods

### ISSUE THREAD

**Issue by makarov-roman** [Foxlider/FASTER#21]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I should manually turn on 40+ mods by clicking on each.

**Describe the solution you'd like**
Add basic control for this. e.g. 
![изображение](https://user-images.githubusercontent.com/11902307/106064812-70352e00-610b-11eb-9280-8ae055a0ec82.png)

**Describe alternatives you've considered**
Toggle all values by click on column header

**Comment by WillBolton45** [comment]
Right click the category...
![image](https://user-images.githubusercontent.com/64915404/106065125-b9c54f00-60f2-11eb-9ceb-d9eba24ef827.png)

**Comment by makarov-roman** [comment]
Wow, this could save me a lot of time :)
