### ISSUE TITLE
Updater: Steam Disconnected 

### ISSUE THREAD

**Issue by loom-framework** [Foxlider/FASTER#210]
**Not possible to use updater**  
This bug showed up after latest Game version: 2.18.152239 update.

Steam just attemting to connect and all time disconnected.

**Comment by Wully616** [comment]
same here

**Comment by OverlordZorn** [comment]
Known issue - devs are working on it. Check the discord if you wanna witness them loose their sanity

**Comment by OverlordZorn** [comment]
this can be considered fixed with the latest release

https://github.com/Foxlider/FASTER/releases

**Comment by OverlordZorn** [comment]
did you try teo clear your sentry data as the warnin suggests?
