### ISSUE TITLE
[BUG] Unable to download large mod

### ISSUE THREAD

**Issue by makarov-roman** [Foxlider/FASTER#22]
**Describe the bug**
I'm not able to download 10gb mod from workshop. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Steam Mods'
2. Click on 'Update mod'
3. Wait

**OS Version (required):**
 - OS: [e.g. Windows 10 20H2]
 - Version [e.g. 1.7a]

**Additional context**
```
Starting SteamCMD to update Addon
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Logging in user 'tryingtotry' to Steam Public ...

Logged in OK
Waiting for user info...OK
Downloading item 583496184 ...ERROR! Timeout downloading item 583496184Redirecting stderr to 'G:\games\SteamCMD\logs\stderr.txt'
[  0%] Checking for available updates...

[----] Verifying installation...

SteamCMD Exited
```
I have stable 100mbit connection/ssd. Tried multiple times.

**Comment by WillBolton45** [comment]
This is a common SteamCMD issue.
Simply keep retrying the download, for 10GB I would assume you need to do it at least ten times.

**Comment by makarov-roman** [comment]
I see. It would be great if Faster handle this specific issue and suggest user to keep trying because it's not very intuitive if partially downloaded data persist trough tries or rolled back. What do you think?

**Comment by Foxlider** [comment]
It is a known error that is present on both FAST2 and FASTER

I am working on a fix of some sort to solve that issue.
For now, just keep trying because SteamCMD can only download 1Gb at a time

**Comment by makarov-roman** [comment]
Pretty big limitation for arma. In this case FASTER could automatically retry to download a mod until succeed. (with maxRetries=filesize/1gb)

**Comment by Foxlider** [comment]
Trust me if it was that easy it would have been done already. SteamCMD is really a pain in the ass. I have requested an unlock directly to SteamCMD's devs many times but without any form of answer
