### ISSUE TITLE
[FEATURE] show launch parameters

### ISSUE THREAD

**Issue by MildlyInterested** [Foxlider/FASTER#23]
Show launch parameters in FASTER "live", similar to how the two config files are being shown in FASTER.
[Example Picture](https://user-images.githubusercontent.com/6746043/62007527-eb5d0300-b167-11e9-9209-09daf903a82c.png)

**Comment by Foxlider** [comment]
I should have thought of that...

**Comment by MildlyInterested** [comment]
Right? 
And while I'm at it please show the headless client launch parameters too.
