### ISSUE TITLE
[BUG] Fails to download performance branch

### ISSUE THREAD

**Issue by MildlyInterested** [Foxlider/FASTER#26]
**Describe the bug**
Unable to download Perfomance/Profiling Branch

**To Reproduce**
Steps to reproduce the behaviour:
1. Steam Updater
2. Version
3. Scroll down to "Perfomance / Profiling"
4. Click update
5. SteamCMD says updating but no files are being downloaded

**Expected behaviour**
`arma3serverprofiling_x64.exe` should appear in arma sever folder.

**Actual behaviour**
It doesn't.

**SteamCMD """"logs""""**
```Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 0.00 (0 / 233593269)
 Update state (0x61) downloading, progress: 95.74 (223632861 / 233593269)
Success! App '233780' fully installed.
Redirecting stderr to 'E:\Arma3_Server\Arma3_steamcmd\logs\stderr.txt
```

**OS Version (required):**
 - OS: Windows Server 2019 Standard 1809
**FASTER Version**
 1.7aH1 

**Additional context**
It should work in your new system :)

**Comment by Foxlider** [comment]
Fingers crossed !
