### ISSUE TITLE
[BUG] Can't delete a server profile

### ISSUE THREAD

**Issue by ZambrOvosky** [Foxlider/FASTER#27]
**Describe the bug**
After creating your brand new profile you can't delete. You just can't find a way to easily delete it.

**Expected behaviour**
It should have a button somewhere, like the previous version when the button was aside the save and play. That can be on the right-click too.

**Actual behaviour**
No button, you just can't.

**Comment by Foxlider** [comment]
Check the Wiki
The Profile Delete Button got moved
https://github.com/Foxlider/FASTER/wiki/Profile-Page

You need to right click the profile name on the profile page
![image](https://user-images.githubusercontent.com/19773387/111757826-0b40bd80-889c-11eb-9dd8-9c941cc88774.png)

**Comment by ZambrOvosky** [comment]
Dude, this thing is hiden af.

**Comment by Foxlider** [comment]
It was stated in the release not and in the Wiki. It had to be moved tho code-wise
