### ISSUE TITLE
[BUG] HOTFIX 1.7a H2 crash on submitting Steam Guard Code

### ISSUE THREAD

**Issue by GoldJohnKing** [Foxlider/FASTER#29]
**Describe the bug**
HOTFIX 1.7a H2 crash on submitting Steam Guard Code.

**To Reproduce**
Steps to reproduce the behaviour:
1. Update to HOTFIX 1.7a H2.
2. Click "Update" on the main interface.
3. Type Steam Guard Code.
4. FASTER hang and crash.

**OS Version (required):**
 - OS: Windows Server 2019
 - Version HOTFIX 1.7a H2

**Comment by Foxlider** [comment]
Ah so that's still a thing...

**Comment by Foxlider** [comment]
https://github.com/Foxlider/FASTER/releases/tag/1.7a_h3
