### ISSUE TITLE
[BUG] Only one headless client launches (Perfomance/Profiling Branch)

### ISSUE THREAD

**Issue by MildlyInterested** [Foxlider/FASTER#30]
**Describe the bug**
Try to launch two headless clients while running performance/profiling branch

**To Reproduce**
Steps to reproduce the behaviour:
1. Set HCs amount to two or above
2. Click on Launch HCs

**Expected behaviour**
All headless clients should launch.

**Actual behaviour**
Only one headless client launches, the other ones get stuck on start up and are shown as "not responding" in task manager.
Caused by:  
> they all want their seperate signature cache (will freeze until the other opens access to it), and profileNamespace

Dedmen (Bohemia Dev) on Discord

**OS Version (required):**
 - OS: Windows Server 2019 Standard 1809
 - FASTER Version 1.7aH3

**Suggested Fix**
iterate the profile launch parameter for headless clients like so:
` "-profiles=E:\Arma3_Server\Arma3\Servers\_aaf3ce999caf4539b903336ded3830fc_HC1"`

**Additional context**
Technically this is the way its supposed to be done in main branch aswell, it just worked for some reason.
This made Will.Bolton45 really sad

**Comment by Foxlider** [comment]
That will need to be fixed on 1.8
