### ISSUE TITLE
[BUG] Copy keys not working for local mods

### ISSUE THREAD

**Issue by MildlyInterested** [Foxlider/FASTER#31]
**Describe the bug**
Copy key function copies keys of all local mods instead of only selected ones.
If there a no steam mods downloaded (only local mods) copy key function does not work at all.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Profile
2. Click on "Copy Mod Keys"
3. Open explorer and check which keys are in the keys folder
4. Extra keys are in there

**Expected behaviour**
Only selected keys should be copied.
Copy key functionality should work with only local mods.

**Actual behaviour**
All local mod keys are copied or none at all (if no steam mods installed)

**OS Version (required):**
- OS: Windows Server 2019 Standard 1809
FASTER Version
1.7aH3

**Additional context**
This makes me really sad

**Comment by Foxlider** [comment]
This is because of how mods are handled since the start of FASTER. This should change with the new incoming version

**Comment by MildlyInterested** [comment]
Oh now I'm getting an answer! :P
