### ISSUE TITLE
[Bug] ARMA Server not visible if too many mods are loaded into FASTER

### ISSUE THREAD

**Issue by 0xlord** [Foxlider/FASTER#33]
**Describe the bug**
Hello, 
I've run into a problem that renders the server invisible on the Arma Launcher:
 * If I have more than 31 mods installed
AND/OR
 * If I have more than 30 mods activated for a single server execution

In both ways, the server can't be found through the launcher but is still connectable with "Direct Connect". This could be reproduced on two separate machines. We are using the 1.7b H3 version on both. Let me know if I can provide more pieces of information.

Thank you for any help.

**To Reproduce**
 * Have more than 31 mods installed
AND/OR
 * Have more than 30 mods activated for a single server execution
 * (Optional) Have HCs set to 2

**Expected behaviour**
Server can be findable in ARMA 3 Launcher again with > 30 mods active/> 31 mods installed

**Actual behaviour**
Server starts fine, Server isn't findable in ARMA 3 Launcher, can be connected through Direct Connect though.

**OS Version (required):**
 - OS: Server 2016
 - Version 1607

**Comment by MildlyInterested** [comment]
That's a steam query limitation. To make it work with more than 31 mods change the `steam protocol max data size` to a higher value like `8192`.
Setting can be found in the "Server Advanced" tab on the "Server" page.

**Comment by 0xlord** [comment]
Can confirm it to be working. 
Off thing is, that so far a max of 4096 was communicated. Less would be better. But if such a value works, then it is fine for us. Odd that none used mods seem to play into this as well somehow. 

Anyway - it works fine now and that's all that matters :-)
Thanks a lot!
