### ISSUE TITLE
[FEATURE] Add support for cDLC S.O.G. Prairie Fire

### ISSUE THREAD

**Issue by dartus95** [Foxlider/FASTER#40]
**Is your feature request related to a problem? Please describe.**
Support for new Creator DLC S.O.G. Prairie Fire

**Additional context**
Hopefully something simillar as it is now for Contact and GM

**Comment by MildlyInterested** [comment]
I _believe_ simply ticking the GM box will download the CDLC server data. 
Steamcmd doesn't care about the difference. There's only one CreatorDLC branch containing all CDLCs so you don't get a choice :D

**Comment by CRCError1970** [comment]
Selecting the CreatorDLC branch does download the DLC, but there is no checkbox for adding it to the mod list.

**Comment by fire-391** [comment]
Dont need to add it to the list of mods, "it just works"

**Comment by CRCError1970** [comment]
> Dont need to add it to the list of mods, "it just works"

Yes, you do. Contact, Global Mobilization and Prairie Fire don't load by default in the FASTER launcher. You have to check them off to load them on the server profile page.

**Comment by dartus95** [comment]
So today I was tinkering with it a little bit and got it working. Downloaded Creator DLC branch, added -mod=vn into the command line arguments on performance tab, and run the server and it is working for me just fine. But it would be nic to have similar button as it is for GM.
![unknown](https://user-images.githubusercontent.com/29777845/117450883-18943300-af42-11eb-828e-22c0970c2f77.png)

**Comment by CRCError1970** [comment]
> So today I was tinkering with it a little bit and got it working. Downloaded Creator DLC branch, added -mod=vn into the command line arguments on performance tab, and run the server and it is working for me just fine. But it would be nic to have similar button as it is for GM.
> ![unknown](https://user-images.githubusercontent.com/29777845/117450883-18943300-af42-11eb-828e-22c0970c2f77.png)

I can't believe I forgot about that option. I was trying to make the vn folder look like an external mod to FASTER. Thanks for reminding me about the CLA field.

**Comment by theace0296** [comment]
@Foxlider  This is fixed as part of #48
