### ISSUE TITLE
[Bug] steam API not connecting when trying to update and load new mods from Steam workshop

### ISSUE THREAD

**Issue by DJGeneralE** [Foxlider/FASTER#42]
Steam updater is working 

Unable to update mods error is could not connect to Steam API

Error when checking for mod updates
![image](https://user-images.githubusercontent.com/85328621/120743439-dfea6980-c4ad-11eb-87c7-33104e5776cf.png)

Error for uploading mods through steam
![image](https://user-images.githubusercontent.com/85328621/120743517-07413680-c4ae-11eb-8164-6a4dfa43678c.png)

Steam CMD 
![image](https://user-images.githubusercontent.com/85328621/120743640-3fe11000-c4ae-11eb-83a9-c4db65450798.png)

if you have any other questions or would like to take a look for diagnostic purposes send me a message on discord 
DJGeneralE#0782

**Comment by Foxlider** [comment]
SteamCMD can overpass API limitations. 
Your API key has a certain amount of uses per hour to avoid bot spams. This key is used by FASTER to check if a mod is up to date by calling Steam Servers.  When this is done, and a mod require updates, SteamCMD is called to update it but SteamCMD is not limited by the API restrictions.

Just wait for the API ratelimit to go under the limit again. 

I highly advise that you use your own API key and avoid checking for update too often
