### ISSUE TITLE
[FEATURE] Filter on key bits like mod path

### ISSUE THREAD

**Issue by mwpowellhtx** [Foxlider/FASTER#43]
Improving convenience, ease of use. Be able to filter on a Mod Name, for instance, that would be fantastic, for starters.

![image](https://user-images.githubusercontent.com/1824187/123702686-700f9a80-d831-11eb-828a-92a07cd5d799.png)

**Comment by Foxlider** [comment]
While it's doable in theory, it's not officially supported and would require an absurd amount of coding. 
It will be kept in mind but not a priority

**Comment by mwpowellhtx** [comment]
Yeah, I appreciate that, probably with severely underpowered vanilla controls, certainly no Telerik or DevExpress backing them up. Thanks...

**Comment by mwpowellhtx** [comment]
Suggest does not have to be fancy pants; even a simple text input that feeds a regex pattern would be adequate to get things started.

**Comment by Foxlider** [comment]
Yeah, I don't have money for Telerik UI...

**Comment by mwpowellhtx** [comment]
@Foxlider OFC, and I wouldn't expect something that fancy, either.

**Comment by SamueleLorefice** [comment]
I'd bump this up saying that a good improvement would be to only show the last folder of the path if the mod name is just the folder path. That would make things easier to start with.

**Comment by mwpowellhtx** [comment]
> I'd bump this up saying that a good improvement would be to only show the last folder of the path if the mod name is just the folder path. That would make things easier to start with.

Or at least from the 'mission' folders out. Not sure it that's the case already, however.
