### ISSUE TITLE
[FEATURE] Add Arma 3 Server install directory

### ISSUE THREAD

**Issue by mwpowellhtx** [Foxlider/FASTER#44]
Maybe more of a question. `Install Directory` is for the base _Arma 3_ instance? Adding `Servers` there seems confusing to me, given there is a separate `Arma 3 Server` install. Would it not be better to spec that folder, i.e. `\Path\To\Program Files (x86)\Steam\steamapps\common\Arma 3 Server`?

**Comment by MildlyInterested** [comment]
The whole tool is made for the server executable. Your use case of running it on top of a normal Arma client install is an egde case. 


In the end it doesn't really matter where the server folder is saved.

**Comment by mwpowellhtx** [comment]
I see, but aren't the client and server technical separate packages? A3 client may provide convenience for purposes of loading locally downloaded mods, but that's the extent of it. For everything else I want to ride on the server instance.

**Comment by Foxlider** [comment]
Arma3 Server and FASTER are supposed to be installed on a different system than the client

**Comment by mwpowellhtx** [comment]
Says who? Best case I would run it in a docker session. However, on my system, really does not need to be separate, either; 16 cores on an AMD TR 2950X.

**Comment by Foxlider** [comment]
Says the guy who coded the whole thing ! 
I can't forbid users to do it but know that this use case is not supported by FASTER and it cannot be held responsible in case of corruption or any issue regarding the use of standard Arma Client instead of the Arma Server it was coded for.
