### ISSUE TITLE
[FEATURE] Add Profiling Branch

### ISSUE THREAD

**Issue by 0xlord** [Foxlider/FASTER#5]
Can you please add support for the performance branch into FASTER? This would be super helpful:

* Branchname: **profiling - Performance﻿ ﻿Profiling﻿﻿ Build**﻿
* Password: **CautionSpecialProfilingAndTestingBranchArma3**﻿﻿﻿﻿﻿﻿
* BI Thread: https://forums.bohemia.net/forums/topic/160288-arma-3-stable-server-198-performance-binary-feedback/

**Comment by Foxlider** [comment]
Fixed in release
