### ISSUE TITLE
[BUG] Updating FASTER Server Profiles Missing

### ISSUE THREAD

**Issue by LaocheXe** [Foxlider/FASTER#50]
**Describe the bug**
Just updated FASTER from 1.6.2.0 to 1.7.1.0, and my Server Profiles are no longer listed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have old version of FASTER
2. Go to Settings, Update FASTER
3. Click Ok
4. After Launching FASTER, Server Profiles aren't listed there.
---
If anything, it should keep the current Server Profiles

**Comment by Foxlider** [comment]
![image](https://user-images.githubusercontent.com/19773387/136673392-bdba6e1d-1811-4123-8844-bad01df70969.png)
You need to use the Maintenance module due to changes on the profile system. It is written on the changelog

**Comment by LaocheXe** [comment]
Just FYI - your check for update doesn't say anything about changelog.
