### ISSUE TITLE
[FEATURE] Allow Steam Workshop Mods to be downloaded to Arma 3 Server Folder instead of SteamCMD Folder

### ISSUE THREAD

**Issue by TandelK** [Foxlider/FASTER#59]
**Is your feature request related to a problem? Please describe.**
Currently the Steam Workshop mods are automatically downloaded in SteamCMD steamapps folder and not in Arma 3 folder. If i run multiple game servers it just gets cluttered in one space. I had been using SteamCMD Batch file before to download the mods to Arma 3 Server Directory with force_install_dir command. FASTER didnt even detect steam workshop  Mods installed in my Arma 3 Server folder so had to download all of them again.

**Describe the solution you'd like**
Allow us to select Location where to download Steam Workshop Mods and than create a Symbolic Link in Arma 3 Server Folder of the same.  

**Describe alternatives you've considered**
Well none as of now.

**Comment by Foxlider** [comment]
That is a definitive no
1. It won't work with how FASTER is coded
2. It's a source of errors and will break things

You can try 1.8 : mods are downloaded to a folder and are linked to your desired Arma folder. 
You can have multiple arma folders and decide what mods to link or not
