### ISSUE TITLE
[BUG] Mutiple annoying issue.

### ISSUE THREAD

**Issue by CALADARI** [Foxlider/FASTER#60]
**Describe the bug**
Issue with mods.
Issue with downloading mods.

**To Reproduce**
Steps to reproduce the behaviour:
Issue One;
1.Import a mod list (in my case i imported 29 mods)
2.Check for update , returns 'Not Installed'
3.Press 'Update all' , wait until all done
Issue Two; 
When I'm manually re-download all these faulted mods by cliking the standalone update buttons...
The update console returned these error and refuse to download them.Restarting OS or FASTER all no use.
```
Failed! Error: Client is faulted and cannot be used: Error code: PasswordRequiredToKickSession
Failed! Error: Client is faulted and cannot be used: Error code: RateLimitExceeded
```
 and now these mods are marked as 'download not completed' in mod list.

**Expected behaviour**
In older version like back into prior WP edition (directly using steamCMD), these mod will be correctly tagged correctly as 'download not complete' or 'not downloaded', should be able to solve by manually download them for mutiple times

**Actual behaviour**
All status shown 'up to date' , yet mutiple mods are actually not downloaded , other few are not fully downloaded. for those not being downloade, The folder are empty and the size are 0.00b. for those are not downloaded pops error message while starting server and thats how i know the download is not completed.
click check for update or update all, no use.

**Screenshots**
mod page
![image](https://user-images.githubusercontent.com/45614593/148683035-e6d4b44f-ead2-4096-ab09-eaed379e9c11.png)
console page
![image](https://user-images.githubusercontent.com/45614593/148683070-35a846f4-debb-4970-b8dc-d4c13819122e.png)
error indicates unfinished mod
![image](https://user-images.githubusercontent.com/45614593/148683163-8bfd6f3e-56d5-4a49-981d-9f775f33735a.png)

**OS Version (required):**
 - OS: Microsoft Windows Server 2019 Datacenter
 - Version	10.0.17763  17763

**Additional context**
Sorry for my terrible grammar or spelling , I'm not a domestic English speaker.
Story in short.
Import the mod list, click update all.
It shows all downloaded. 
Error pops out when addon init.
Check mod list , found 0.00b mods
Try solve these faulty mod by manually click update button one by one.
Console returns error , cant proceed.
Now sitting here writing this issue report despirately with my poor rubbish English.

**Comment by Foxlider** [comment]
Oh I see
I'll work on it then

**Comment by CALADARI** [comment]
Update:

I managed to kick the FASTER's login down by cancel all authorized devices via steam setting.
So that's 'PasswordRequiredToKickSession' issue. FYI to anyone who suffered from same issue.
I know there is a warning said 'Do NOT shut down FASTER while updating', while a debug option which loging out FASTER's steam login maybe added in later update?

I'm now manually updating mods via the standalone update button.
To give a clearer description of the issue , here I supply some extra screenshot .
first I clicke 'check for update' & 'update all'.
![image](https://user-images.githubusercontent.com/45614593/148746427-424a841d-21d9-4a26-81c5-605e54ed6e11.png)
the console returns 'all updated';then I manually update , in this case, RHSAFRF.
![image](https://user-images.githubusercontent.com/45614593/148746545-5d3422e3-4868-4ce9-9964-32b6882fa497.png)
![image](https://user-images.githubusercontent.com/45614593/148746891-42c7d243-6b9d-402a-8e14-797b501081c4.png)
we can see still 6 unfinished(1.08GB) files here.
