### ISSUE TITLE
[BUG] Can't download WS DLC

### ISSUE THREAD

**Issue by CALADARI** [Foxlider/FASTER#61]
Starting Update...
Please don't quit this page or cancel the download
This might take a while...
Downloading Shared Content...
Connecting to Steam as 【myaccount】
OK.
Error: A task was canceled.
Downloading Executables...
Connecting to Steam as 【myaccount】
OK.
Attempting to start download of app 233780, depot 233782... 
OK.
Downloading 0 files with total size of    0.00  B...
Verification completed, 0 files queued for download. (0 bytes)
Download completed
Progress 00.00%
Done in 0h 0m 11s 939ms
Downloading Arma 3 Server Creator DLC - Western Sahara...
Connecting to Steam as 【myaccount】
OK.
Error: Depot 233786 not found.

All Done !

**Comment by Foxlider** [comment]
Known issue

Steam changed the depot ID for some DLCs and it fucked up with 1.8's system
Fix underway
