### ISSUE TITLE
[BUG] UI turned into white somehow.

### ISSUE THREAD

**Issue by CALADARI** [Foxlider/FASTER#62]
**Describe the bug**
UI will randomly turn into white color , sometimes resotred after swithching pages , sometimes don't until restart FASTER.

**To Reproduce**
Steps to reproduce the behaviour:
Just randomly swithing between pages.

**Screenshots**
![image](https://user-images.githubusercontent.com/45614593/149333346-55be5ede-89f5-4331-af07-e9b8d8f502fa.png)
for now I only have this screenshot, but it do happens to Profile and Mods page.I'll attach em later if I encounter.

**OS Version (required):**
- OS: Microsoft Windows Server 2019 Datacenter
- Version 10.0.17763 17763

**Comment by CALADARI** [comment]
![image](https://user-images.githubusercontent.com/45614593/149333713-2f38cfe8-d93b-48bc-802f-87a3487c9815.png)

**Comment by Foxlider** [comment]
Known issue due to how RDP is made. 
RDP doesn't use the PC's chiptset for rendering but uses a dedicated lightweight driver that can fuck up sometimes with rendering. 

I'm working on a fix but no guarantees
