### ISSUE TITLE
[FEATURE] Move Starting of Server -mod to parameter file instead of direct launch. 

### ISSUE THREAD

**Issue by TandelK** [Foxlider/FASTER#63]
**Is your feature request related to a problem? Please describe.**
Currently it uses Steam Mods name as folder on Arma 3 server, some of the mods wont load due to Steam Protocol issue. Would recommend shifting Launching of Server with Parameter File instead of direct Launch method with -mod=

**Describe the solution you'd like**
For Mods create a new Parameter File and use that Parameter file to load the mods to the server. 
Reference : [Startup Parameter Config ](https://community.bistudio.com/wiki/Startup_Parameters_Config_File)

**Describe alternatives you've considered**
None

**Additional context**
Nothing.

**Comment by darwinscusp** [comment]
...and one would accomplish that how?

**Comment by Foxlider** [comment]
![image](https://user-images.githubusercontent.com/19773387/158179256-46a6c742-6cb7-4dd7-ba2a-1f805f4a147d.png)
Change the value of the "Steam Protocol Max Data Size" field

**Comment by TandelK** [comment]
It worked after i had changed the information you had given above. Closing the issue Thanks a lot
