### ISSUE TITLE
[BUG] Local Mods no longer populating Mods list

### ISSUE THREAD

**Issue by derl30n** [Foxlider/FASTER#68]
**Describe the bug**
Just accidentally updated my faster version and I am now unable to see my local mods in the mods overview...

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
See (~70) mods in the mods list...

**Actual behaviour**
list empty...

**Screenshots**
![image](https://user-images.githubusercontent.com/1857322/159188370-8e23b1bf-85ed-4d29-900e-6b47b4085d52.png)
![image](https://user-images.githubusercontent.com/1857322/159188376-86169f86-8859-4f56-9a8b-a0a00aa7d350.png)

**OS Version (required):**
 - OS: Windows 10 19043.1586

**Additional context**
"Copy local mod" is not feasible since it's copying the mods folder instead of using sym link or smth like that.

**Comment by derl30n** [comment]
For now reverted to https://github.com/Foxlider/FASTER/releases/tag/1.7c_ as this version supports local mods and does not require them to be copied somewhere else..

**Comment by Foxlider** [comment]
1.8 is supporting local mods differently : 

Local mods must be added from the modlist. The local mods selector in the settings is something I forgot to remove.

You will notice that in the Modlist there is a new button on top to add a local mod. It will be linked to the mod deployment folder like any other mod and given an ID. 
This is made to make sure mod install is simpler and more stable. 
Think of it l'île Nexus Mod Manager way of doing it

**Comment by derl30n** [comment]
Well it is hard copying the mods folder instead of actually using symlinks. Using the new version you end up with two different versions of the local mod.
It also consumes disk space btw..

**Comment by Foxlider** [comment]
Use this beta version 

1.8b just copies the local mod to the Mod Staging Folder so the user can delete the original one afterwards. 
Users complained about this so I changed it in the beta : 
Local mods are symlinked to the Mod Staged Folder, keeping the original and not consuming space.



https://install.appcenter.ms/users/keelah/apps/faster-1/distribution_groups/public/releases/6

**Comment by derl30n** [comment]
well the downside with actually copying the local mods is, when they are managed and updated via a 3rd party program, so I appreciate the functionality has been added again since it's pretty much mandatory. Otherwise whenever local mods "change/update" you'd have to manually delete and update them.

Thanks for your efforts!

**Comment by Foxlider** [comment]
This is why I advise using the Beta version I linked

The beta version uses Symlinks instead
