### ISSUE TITLE
[BUG] The process cannot access the file 'C:\steamcmd\steamapps\common\Arma 3 Server\arma3server.exe' because it is being used by another process.

### ISSUE THREAD

**Issue by Drift91** [Foxlider/FASTER#69]
**Describe the bug**
For some reason I'm getting an error saying that the files are already in use when I attempt to update the game after updating FASTER to 1.8b. I believe I was previously using either 1.7a H5 or 1.7c. When I check what program has the files in use via ProcessExplorer it can't find any open handles for those files.

**To Reproduce**
Not sure, I simply click "Update" and it craps out.

**Expected behaviour**
For the update to download without error.

**Actual behaviour**
The download fails.

**Screenshots**
![image](https://user-images.githubusercontent.com/2638764/160713374-3f24d8a6-5259-4051-8859-8d528bcf12de.png)

**OS Version (required):**
 - Windows Server 2022 (21H2)
 - 1.8b

**Additional context**
N/A

**Comment by Drift91** [comment]
I've successfully updated the server manually through SteamCMD but now FASTER is refusing to download the mods.

https://pastebin.com/6PKeBE6g
Another issue that needs to be looked into is the fact that all the mods are now marked as "up to date" after failing to download as seen above.

**Comment by Drift91** [comment]
Is FASTER no longer using SteamCMD? It asked me for my 2FA despite the fact that I've got my credentials cached with SteamCMD. And for some reason I'm no longer able to download workshop mods on my alt account that doesn't own the game, which previously wasn't an issue with SteamCMD; This is what caused the error downloading mods in the pastebin paste above. I'm unable to test if the initial error I was having is now fixed when I use my main account, since the game is already up-to-date.

**Comment by Drift91** [comment]
The mods are downloading now, but is there some way to manually select a download server? I've always had major problems with the local server that Steam selects geographically and the next-nearest server has far better ping and bandwidth so I usually select it instead by editing my SteamCMD's `config.vdf`.

**Comment by polat0almdar** [comment]
still having same issue
do you have a solution?

**Comment by Foxlider** [comment]
So far the only solution is to delete the locked files when FASTER is closed and to redownload them by hitting update. 
The beta version seem to have that fixed so I recommend using it : 
https://install.appcenter.ms/users/keelah/apps/faster-1/distribution_groups/public/releases/6

**Comment by Drift91** [comment]
Thanks, that version seems to not have the issue anymore.
