### ISSUE TITLE
[BUG] CDLC keys not copied

### ISSUE THREAD

**Issue by MildlyInterested** [Foxlider/FASTER#78]
**Describe the bug**  
Selected CDLCs in the server profile do not get their key copied with the "copy keys" button.

**To Reproduce**  
Steps to reproduce the behaviour:
1. Go to 'Server Profile'
2. Select a CDLC from the "DLCs" dropdown
3. Click on "Copy Mods Keys"
4. Key does not get copied

**Expected behaviour**  
CDLC key to be copied to armas "keys" folder.

**Actual behaviour**  
not being copied

**Screenshots**  

**OS Version (required):**  
 - OS: Windows Server 2016 v1809
 - FASTER Version 1.8d

**Comment by jupster** [comment]
Pretty sure this can be closed https://github.com/Foxlider/FASTER/blob/f4492316393656b8f5fe591d1ed7f2cd1cdf99ad/FASTER/ViewModel/ProfileViewModel.cs#L390C13-L390C13
