### ISSUE TITLE
[BUG] Shaders not valid

### ISSUE THREAD

**Issue by WACHAmaru** [Foxlider/FASTER#83]
Faster →updater →update →all done →Arma3 launcher → new server →[Shaders not valid] error
why???????????

I cannot launch the arma3.

- OS: [e.g. Windows 10 21H2]
 - FASTER Version [e.g. 1.8d(latest)]

**Comment by WACHAmaru** [comment]
I tested that game for integrity and that game had errors.
After correct the data, I used faster again, but again the error occurred.
infinite loop!! help me!!!

**Comment by WACHAmaru** [comment]
Updater means to start up the server, right?
I am Japanese, so I am not familiar with English....

**Comment by Foxlider** [comment]
Make sure you have the required dlls, DirectX etc. Read the documentation and the get started from the wiki : [wiki link](https://github.com/Foxlider/FASTER/wiki)

**Comment by WACHAmaru** [comment]
I was finding the wiki!
Thank you so much.
Also I could launch server.
I was mistaken about how to set up the server.
Sorry for bothering you.
