### ISSUE TITLE
[BUG] Can't fetch mod infos

### ISSUE THREAD

**Issue by Mitgammer** [Foxlider/FASTER#84]
Description:
+ I used faster for hosting and maintaining my arma server for a few days now and suddenly when I tried to update a mod it just says:
"Connecting to Steam as (username)
Connected !
Fetching mod (mod ID) infos..." 
 and nothing else
Reproduce: 
+ I'm not sure how this could be my own connectivity issue or steam's but still in the picture below I tried updating ACE3 but nothing happens 
![Screenshot (193)](https://user-images.githubusercontent.com/106250103/170265574-1f436c46-5eef-4a5e-afa0-16f50d6b4ba6.png)

**Comment by Foxlider** [comment]
Try deleting the `sentries` folder in your AppData folder. You can access it from the tool menu top right corner. 
`%localappdata%\FoxliCorp\FASTER_StrongName_someStuffHere\yourVersion`

**Comment by Mitgammer** [comment]
I deleted the Sentences folder and tried to update the mod it asked for key I got it but then it's the same problem

**Comment by Mitgammer** [comment]
FIX: restart pc and make sure steam verifies it's update
