### ISSUE TITLE
Server launching with a max player limit of 0 players, regardless of actual number in FASTER settings.

### ISSUE THREAD

**Issue by Woffingshire** [Foxlider/FASTER#85]
**Describe the bug**  
My server once launched says that the max player limit on the server is 0, regardless of what it is actually set to in the FASTER settings.

**To Reproduce**  
Steps to reproduce the behaviour:
1. Go to server profle
2. Increase the max player count to any number
3. launch the server
4. Try and join the server in ARMA 3

**Expected behaviour**  
The server should be detected and, until a player joins, show a player count of 0/(max number of players). You should then be able to join the server.

**Actual behaviour**  
The server is detected but shows a player count of 0. Just 0. When a player tries to join they recieve the message "Maximum number of players reached" and then are returned to the main menu

 - OS: Windows 11
 - FASTER Version 1.8d

**Additional context**  
Strange behaviour with headless clients. If a headless client is launched at the same time as the server,  the HC is able to join. However if the HC is launched after the server, it also gets hit with the player limit message.

**Comment by Foxlider** [comment]
Check RPT for missing mod or broken mission

**Comment by thehonorguard** [comment]
had this issue before, but appeared to be corrupted/missing mod ;-)

**Comment by Foxlider** [comment]
No more comments from user, closing issue
