### ISSUE TITLE
[FEATURE] Programmatic / CLI Control

### ISSUE THREAD

**Issue by TheSavageCoder** [Foxlider/FASTER#88]
**Is your feature request related to a problem? Please describe.**  
I currently have to expose admin RDP credentials to login to the Windows Server and manage my Arma 3 servers. I want to be able to create/delete servers, download server/mod updates, modify mission/mod lists, start/stop server using remotely execute CLIs or Programmatic HTTP APIs.

**Describe the solution you'd like**  
Be able to have an automated process login remotely and execute CMD or PowerShell commands to interact with FASTER.

**Describe alternatives you've considered**  
Dropping FASTER for command-line-only or using a game server management service (ie, WindowsGSM) to manage the Arma servers

**Additional context**

**Comment by Foxlider** [comment]
FASTER will probably not have this feature because of how the whole project is designed. 
But KAST have this feature in mind though
