### ISSUE TITLE
[FEATURE] Changing the ModStagingDirectory Folder

### ISSUE THREAD

**Issue by SkyHighPurchase** [Foxlider/FASTER#92]
**Is your feature request related to a problem? Please describe.**  
I have a considerably small C Drive. Maybe less than 100gb. It's already full. And having the ModStagingDirectory in the documents tab is just not going to work when I have maybe 85 or so Arma mods I need to put on the server. 

**Describe the solution you'd like**  
The ability to change where the ModStagingDirectory goes would be wonderful.

**Comment by Foxlider** [comment]
You can
On the first Input field of the Console Page
![image](https://user-images.githubusercontent.com/19773387/193844146-979fc0d0-5df6-45a1-b4c2-8a2d67a2fa7e.png)

**Comment by SkyHighPurchase** [comment]
Oh thank god. I must have not seen that, sorry. I'll close this.

**Comment by Foxlider** [comment]
Too fast for you ;)
