### ISSUE TITLE
"You are logged in on another computer playing "Arma 3"

### ISSUE THREAD

**Issue by Razatop** [Foxlider/FASTER#97]
**Describe the bug**  
When Hosting the server on a seperate PC meant for hosting servers. When trying to launch A3 with the server up I can only play the game or host the server.

**To Reproduce**  
Steps to reproduce the behaviour:
1. Launch server
2. Launch game
3. Get Error

**Expected behaviour**  
Being able to launch the game and play on the server

**Actual behaviour**  
Getting kicked out from one.

**Screenshots**  
![image](https://user-images.githubusercontent.com/43615000/211214239-b991df6b-c7c0-4a53-8b00-11fa16fb413b.png)

**OS Version (required):**  
 - OS: Both Server and PC are on Windows 10 pro 21H2
 - FASTER Version 1.8e

**Additional context**

**Comment by MildlyInterested** [comment]
the arma server.exe does not require you to own arma so that error doesn't make sense. Could you upload the server.rpt?

**Comment by Razatop** [comment]
So this was only happening to my personal computer when steam was running with the server open on the server PC. Closed it out and fixed it. Closing the case.
