### ISSUE TITLE
Admin IDs function doesn't work

### ISSUE THREAD

**Issue by foran7** [Foxlider/FASTER#98]
**Describe the bug**  
Key-in Admin IDs doesn't work when I connect to my server, I need to be admin to setup game.

**To Reproduce**  
Steps to reproduce the behaviour:
1. type-in my steam Admin ID on FASTER
2. run server
3. connect to my server
4. didn't become admin

**Expected behaviour**  
I need to be admin to setup game.

**Actual behaviour**  
as a player

**OS Version (required):**  
 - OS: [Windows 10 21H2]
 - FASTER Version [1.851]

Thanks

**Comment by MildlyInterested** [comment]
You still need to type in `#login` in chat to actually become admin, see arma server documentation. It's also mentioned in the setup guide.

**Comment by MildlyInterested** [comment]
https://github.com/Foxlider/FASTER/wiki/FAQ#i-addded-my-steam64id-to-the-admin-ids-but-im-not-admin

**Comment by foran7** [comment]
YES !!  it works ! 
and 1. should I set admin ID also ?
2. what's the function of it (admin ID) ?
**Thank you so much !!**

**Comment by MildlyInterested** [comment]
Please join the discord for support and/or read the FAQ and setup guide here: https://github.com/Foxlider/FASTER/wiki
Github tickets aren't really suitable for conversation.

**Comment by Foxlider** [comment]
Closed after resolution
